services:
  - type: web
    name: cursos-academicos-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://cursos-academicos-backend.onrender.com
